---
- hosts: all
  become: yes
  roles:
    - name: facts

# Build slurm first on all nodes
- hosts: slurm-cluster
  become: yes
  tasks:
    - name: build slurm on all nodes
      include_role:
        name: slurm
        tasks_from: build

# Configure slurm.conf on all nodes
- hosts: slurm-cluster
  become: yes
  roles:
    - name: slurm
      vars:
        user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        slurm_workflow_build: no

